apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-admin
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-admin
  template:
    metadata:
      labels:
        name: strimzi-admin
    spec:
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/sknot/strimzi-admin:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: VERTXWEB_ENVIRONMENT
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  name: strimzi-admin-service
  labels:
    app: strimzi
spec:
  ports:
    - name: admin
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: strimzi-admin
  type: ClusterIP